exclude:
  - vendor/*
  - node_modules/*
  - 'db/schema.rb'
  - "bin/**"
  - "db/migrate/**"
  - 'app/views/devise/**' 
  - 'app/views/layouts/mailer.html.slim'
  - 'app/views/pwa/**/*'


linters:

  LineLength:
    max: 1000
  EmptyLines:
    enabled: true

  Tab:
    enabled: true

  RedundantDiv:
    enabled: true
  
  CommentControlStatement:
    enabled: false  
  
  RuboCop:
    enabled: false
